repos:
  - repo: local
    hooks:
      - id: check-zip
        name: Check Zip
        language: python
        entry: python -m scripts.check-zip
        args: [2.0.1, accounts, business, consents, credit-card, financings, invoice-financings, loans, personal, resources, unarranged-overdraft]
        exclude: ".*"
        always_run: true