name: pre-commit
on: [push]
jobs:
  pre-commit:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.6"
      - name: check-zip
        run: |
          python -m scripts.check-zip